# Generated by Django 2.1.4 on 2018-12-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('a1_1', models.IntegerField(default=0)),
                ('a1_2', models.IntegerField(default=0)),
                ('a1_3', models.IntegerField(default=0)),
                ('a1_4', models.IntegerField(default=0)),
                ('a1_5', models.IntegerField(default=0)),
                ('a1_6', models.IntegerField(default=0)),
                ('a1_7', models.IntegerField(default=0)),
                ('a1_8', models.IntegerField(default=0)),
                ('a1_9', models.IntegerField(default=0)),
                ('a1_10', models.IntegerField(default=0)),
                ('a1_11', models.IntegerField(default=0)),
                ('a1_12', models.IntegerField(default=0)),
                ('a1_13', models.IntegerField(default=0)),
                ('a1_14', models.IntegerField(default=0)),
                ('a1_15', models.IntegerField(default=0)),
                ('a1_16', models.IntegerField(default=0)),
                ('a1_17', models.IntegerField(default=0)),
                ('a1_18', models.IntegerField(default=0)),
                ('a1_19', models.IntegerField(default=0)),
                ('a1_20', models.IntegerField(default=0)),
                ('a1_21', models.IntegerField(default=0)),
                ('a1_22', models.IntegerField(default=0)),
                ('a1_23', models.IntegerField(default=0)),
                ('a1_24', models.IntegerField(default=0)),
                ('a1_25', models.IntegerField(default=0)),
                ('a1_26', models.IntegerField(default=0)),
                ('a1_27', models.IntegerField(default=0)),
                ('a1_28', models.IntegerField(default=0)),
                ('a1_29', models.IntegerField(default=0)),
                ('a1_30', models.IntegerField(default=0)),
                ('a1_31', models.IntegerField(default=0)),
                ('a1_32', models.IntegerField(default=0)),
                ('a1_33', models.IntegerField(default=0)),
                ('a1_34', models.IntegerField(default=0)),
                ('a1_35', models.IntegerField(default=0)),
                ('a1_36', models.IntegerField(default=0)),
                ('a1_text', models.TextField(max_length=200)),
                ('a2_1', models.IntegerField(default=0)),
                ('a2_2', models.IntegerField(default=0)),
                ('a3_1', models.IntegerField(default=0)),
                ('a3_2', models.IntegerField(default=0)),
                ('a3_3', models.IntegerField(default=0)),
                ('a3_4', models.IntegerField(default=0)),
                ('a3_text', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Question'),
        ),
    ]
